steps:

# Build Docker image
- name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "-t",
      "europe-west2-docker.pkg.dev/$PROJECT_ID/jobmesh-backend/api:$COMMIT_SHA",
      "./backend/API/JobMesh.Api/"
    ]

# Push image
- name: gcr.io/cloud-builders/docker
  args:
    [
      "push",
      "europe-west2-docker.pkg.dev/$PROJECT_ID/jobmesh-backend/api:$COMMIT_SHA"
    ]

images:
- europe-west2-docker.pkg.dev/$PROJECT_ID/jobmesh-backend/api:$COMMIT_SHA